import Foundation
import SwiftUI
import UIKit

struct HealthReportInput {
    let startDate: Date
    let endDate: Date
    let patientName: String
    let patientAge: Int
    let patientGender: String
    let medicines: [Medicine]
    let medicineLogs: [MedicineLog]
    let healthRecords: [HealthRecord]
    let womensLogs: [WomensHealthDailyLog]
    let periodCycles: [PeriodCycle]
    let pregnancyProfiles: [PregnancyProfile]
    let pregnancySymptoms: [PregnancySymptomLog]
    let appointments: [DoctorAppointment]
    let appleHealthSummary: DoctorReportAppleHealthSummary?
}

struct HealthReportGenerator {
    private let pageRect = CGRect(x: 0, y: 0, width: 612, height: 792)
    private let margin: CGFloat = 42
    private let footer = "Generated by Tablets app - Informational only. Not medical advice."

    func generate(input: HealthReportInput) throws -> URL {
        let url = FileManager.default.temporaryDirectory
            .appending(path: "Tablets-Health-Report-\(UUID().uuidString).pdf")
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)

        try renderer.writePDF(to: url) { context in
            var y = beginPage(context, input: input)

            section("Blood Pressure", y: &y)
            let bpRecords = input.healthRecords.filter { $0.type == .bloodPressure }
            summaryRows([
                ("Readings", "\(bpRecords.count)"),
                ("Average", averageBP(bpRecords)),
                ("Date range", "\(input.startDate.formatted(date: .abbreviated, time: .omitted)) - \(input.endDate.formatted(date: .abbreviated, time: .omitted))")
            ], y: &y)
            lineChart(title: "BP trend", values: bpRecords.map(\.value1), y: &y)

            ensureSpace(&y, context: context, input: input)
            section("Blood Sugar", y: &y)
            let sugarRecords = input.healthRecords.filter { $0.type == .bloodSugar }
            summaryRows([
                ("Readings", "\(sugarRecords.count)"),
                ("Average", average(sugarRecords.map(\.value1), unit: "mg/dL")),
                ("Latest type", sugarRecords.first?.sugarTestType?.title ?? "Not added")
            ], y: &y)
            lineChart(title: "Sugar trend", values: sugarRecords.map(\.value1), y: &y)

            ensureSpace(&y, context: context, input: input)
            section("Medicines", y: &y)
            let activeMedicines = input.medicines.filter(\.isActive)
            let taken = input.medicineLogs.filter { $0.status == .taken }.count
            summaryRows([
                ("Active medicines", "\(activeMedicines.count)"),
                ("Doses logged taken", "\(taken)"),
                ("Other dose logs", "\(max(input.medicineLogs.count - taken, 0))")
            ], y: &y)
            activeMedicines.prefix(8).forEach { bullet("\($0.name) - \($0.dosage) - \($0.frequencyType.title)", y: &y) }

            ensureSpace(&y, context: context, input: input)
            section("Symptoms", y: &y)
            let symptomCounts = Dictionary(grouping: input.healthRecords.flatMap(\.symptoms) + input.womensLogs.flatMap(\.symptoms), by: { $0 })
                .map { ($0.key, $0.value.count) }
                .sorted { $0.1 > $1.1 }
            if symptomCounts.isEmpty {
                bullet("No symptom logs in this range.", y: &y)
            } else {
                symptomCounts.prefix(8).forEach { bullet("\($0.0): \($0.1)", y: &y) }
            }

            if UserHealthProfile.showWomensHealthCard && (!input.womensLogs.isEmpty || !input.periodCycles.isEmpty) {
                ensureSpace(&y, context: context, input: input)
                section("Women's Health", y: &y)
                summaryRows([
                    ("Period cycles", "\(input.periodCycles.count)"),
                    ("Daily logs", "\(input.womensLogs.count)"),
                    ("Recent symptoms", input.womensLogs.first?.symptoms.prefix(3).joined(separator: ", ") ?? "Not added")
                ], y: &y)
            }

            if let pregnancy = input.pregnancyProfiles.first(where: \.isActive) {
                ensureSpace(&y, context: context, input: input)
                section("Pregnancy", y: &y)
                summaryRows([
                    ("Current week", "\(pregnancy.currentWeek)"),
                    ("Due date", pregnancy.dueDate.formatted(date: .abbreviated, time: .omitted)),
                    ("Symptom logs", "\(input.pregnancySymptoms.count)")
                ], y: &y)
            }

            ensureSpace(&y, context: context, input: input)
            section("Doctor Visits", y: &y)
            if input.appointments.isEmpty {
                bullet("No doctor visit notes in this range.", y: &y)
            } else {
                input.appointments.prefix(6).forEach {
                    bullet("\($0.appointmentDate.formatted(date: .abbreviated, time: .shortened)): \($0.doctorName.isEmpty ? "Doctor visit" : $0.doctorName)", y: &y)
                }
            }

            if let appleHealth = input.appleHealthSummary {
                ensureSpace(&y, context: context, input: input)
                section("Apple Health Summary", y: &y)
                summaryRows([
                    ("Average steps", appleHealth.averageSteps.map { "\(Int($0))" } ?? "Not available"),
                    ("Average sleep", appleHealth.averageSleepHours.map { String(format: "%.1f hrs", $0) } ?? "Not available"),
                    ("Latest heart rate", appleHealth.latestHeartRate.map { "\(Int($0)) bpm" } ?? "Not available")
                ], y: &y)
            }

            drawFooter()
        }

        return url
    }

    private func beginPage(_ context: UIGraphicsPDFRendererContext, input: HealthReportInput) -> CGFloat {
        context.beginPage()
        draw("Tablets - Personal Health Report", at: CGPoint(x: margin, y: 36), font: .boldSystemFont(ofSize: 23), color: UIColor(AppColor.medicalBlueDeep))
        draw("Patient: \(input.patientName.isEmpty ? "Not added" : input.patientName) | Age: \(input.patientAge > 0 ? "\(input.patientAge)" : "Not added") | Gender: \(input.patientGender)", at: CGPoint(x: margin, y: 66), width: 528, font: .systemFont(ofSize: 10), color: .darkGray)
        draw("Range: \(input.startDate.formatted(date: .abbreviated, time: .omitted)) - \(input.endDate.formatted(date: .abbreviated, time: .omitted)) | Generated: \(Date().formatted(date: .abbreviated, time: .shortened))", at: CGPoint(x: margin, y: 82), width: 528, font: .systemFont(ofSize: 10), color: .darkGray)
        draw("This report is based on your saved logs and is informational only. Please review it with your doctor.", at: CGPoint(x: margin, y: 104), width: 528, font: .systemFont(ofSize: 10), color: .darkGray)
        drawFooter()
        return 132
    }

    private func ensureSpace(_ y: inout CGFloat, context: UIGraphicsPDFRendererContext, input: HealthReportInput, needed: CGFloat = 135) {
        if y + needed > 710 {
            y = beginPage(context, input: input)
        }
    }

    private func section(_ text: String, y: inout CGFloat) {
        draw(text, at: CGPoint(x: margin, y: y), font: .boldSystemFont(ofSize: 15), color: UIColor(AppColor.medicalBlueDeep))
        y += 22
    }

    private func summaryRows(_ rows: [(String, String)], y: inout CGFloat) {
        for row in rows {
            draw(row.0, at: CGPoint(x: margin + 10, y: y), font: .boldSystemFont(ofSize: 10), color: .darkGray)
            draw(row.1, at: CGPoint(x: 190, y: y), width: 350, font: .systemFont(ofSize: 10), color: .black)
            y += 16
        }
    }

    private func bullet(_ text: String, y: inout CGFloat) {
        draw("- \(text)", at: CGPoint(x: margin + 12, y: y), width: 500, font: .systemFont(ofSize: 10), color: .black)
        y += 15
    }

    private func lineChart(title: String, values: [Double], y: inout CGFloat) {
        draw(title, at: CGPoint(x: margin + 10, y: y), font: .boldSystemFont(ofSize: 10), color: .darkGray)
        y += 14
        guard values.count >= 2 else {
            draw("Not enough data for trend", at: CGPoint(x: margin + 10, y: y), font: .systemFont(ofSize: 10), color: .darkGray)
            y += 22
            return
        }

        let rect = CGRect(x: margin + 10, y: y, width: 500, height: 74)
        UIColor.systemGray5.setStroke()
        UIBezierPath(rect: rect).stroke()
        let minValue = values.min() ?? 0
        let maxValue = values.max() ?? 1
        let range = max(maxValue - minValue, 1)
        let path = UIBezierPath()
        for (index, value) in values.enumerated() {
            let x = rect.minX + CGFloat(index) / CGFloat(values.count - 1) * rect.width
            let scaled = (value - minValue) / range
            let point = CGPoint(x: x, y: rect.maxY - CGFloat(scaled) * rect.height)
            index == 0 ? path.move(to: point) : path.addLine(to: point)
        }
        UIColor(AppColor.medicalBlueDeep).setStroke()
        path.lineWidth = 2
        path.stroke()
        y += 92
    }

    private func drawFooter() {
        draw(footer, at: CGPoint(x: margin, y: 724), width: 528, font: .systemFont(ofSize: 9), color: .darkGray)
    }

    private func averageBP(_ records: [HealthRecord]) -> String {
        let usable = records.filter { $0.value2 != nil }
        guard usable.isEmpty == false else { return "No logs" }
        let systolic = usable.map(\.value1).reduce(0, +) / Double(usable.count)
        let diastolic = usable.compactMap(\.value2).reduce(0, +) / Double(usable.count)
        return "\(Int(systolic.rounded()))/\(Int(diastolic.rounded())) mmHg"
    }

    private func average(_ values: [Double], unit: String) -> String {
        guard values.isEmpty == false else { return "No logs" }
        return "\(Int((values.reduce(0, +) / Double(values.count)).rounded())) \(unit)"
    }

    private func draw(_ text: String, at point: CGPoint, width: CGFloat = 520, font: UIFont, color: UIColor) {
        let attributes: [NSAttributedString.Key: Any] = [.font: font, .foregroundColor: color]
        text.draw(in: CGRect(x: point.x, y: point.y, width: width, height: 110), withAttributes: attributes)
    }
}
