import Foundation

struct HinglishNormalizer {
    func normalize(_ text: String) -> String {
        var normalized = text.lowercased()
        mappings.forEach { source, replacement in
            let escaped = NSRegularExpression.escapedPattern(for: source)
            normalized = normalized.replacingOccurrences(of: "(?<![a-z0-9])\(escaped)(?![a-z0-9])", with: replacement, options: .regularExpression)
        }
        normalized = normalized.replacingOccurrences(of: #"\s+"#, with: " ", options: .regularExpression)
        return normalized.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private let mappings: [(String, String)] = [
        // Health terms
        ("dawaiya", "medicines"),
        ("dawaiyan", "medicines"),
        ("dawai", "medicine"),
        ("dawa", "medicine"),
        ("goliyan", "tablets"),
        ("goli", "tablet"),
        ("capsul", "capsule"),
        ("sirap", "syrup"),

        // Taking medicine
        ("tablet kha liya", "i took my tablet"),
        ("tablet khaya", "i took my tablet"),
        ("tablet li", "i took my tablet"),
        ("dawai li", "i took my medicine"),
        ("dawa kha liya", "i took my medicine"),
        ("goli kha li", "i took my tablet"),
        ("tablet lena hai", "i need to take tablet"),
        ("dawai leni hai", "i need to take medicine"),
        ("kaunsa tablet lena hai", "which tablet should i take"),
        ("koi tablet pending", "any tablet pending"),
        ("tablet pending hai", "tablet is pending"),
        ("kya tablet liya", "did i take my tablet"),
        ("tablet liya kya", "did i take my tablet"),
        ("subah ka tablet", "morning tablet"),
        ("raat ka tablet", "night tablet"),
        ("dopahar ka tablet", "afternoon tablet"),
        ("sham ka tablet", "evening tablet"),

        // BP / blood pressure
        ("tension kaisa hai", "how is my blood pressure"),
        ("tension kitna hai", "what is my blood pressure"),
        ("pressure kaisa hai", "how is my blood pressure"),
        ("pressure kitna hai", "what is my blood pressure"),
        ("bp hai mera", "my bp is"),
        ("mera bp", "my bp"),
        ("tension hai", "blood pressure"),
        ("bp high hai", "my bp is high"),
        ("bp low hai", "my bp is low"),
        ("bp check karna hai", "i want to check bp"),
        ("bp record karna hai", "record bp"),

        // Sugar
        ("khane ke baad sugar", "sugar after food"),
        ("khane se pehle sugar", "sugar before food"),
        ("sugar check karna hai", "i want to check sugar"),
        ("sugar record karna hai", "record sugar"),
        ("sugar hai mera", "my sugar is"),
        ("mera sugar", "my sugar"),
        ("sugar kitna hai", "what is my sugar"),
        ("sugar kaisa hai", "how is my sugar"),
        ("diabetes hai mujhe", "i have diabetes"),
        ("meetha khaya", "ate sweets"),
        ("fasting sugar", "fasting sugar"),
        ("sugar high hai", "sugar is high"),
        ("sugar low hai", "sugar is low"),

        // Symptoms
        ("sar mein dard", "i have headache"),
        ("sar dard hai", "i have headache"),
        ("sar dard", "headache"),
        ("sir dard hai", "i have headache"),
        ("sir dard", "headache"),
        ("chakkar aa raha", "i have dizziness"),
        ("chakkar aa rahi", "i have dizziness"),
        ("chakkar aata hai", "i have dizziness"),
        ("chakkar hai", "i have dizziness"),
        ("bahut thak gaya", "i am very tired"),
        ("bahut thak gayi", "i am very tired"),
        ("thaka hua", "i am tired"),
        ("thaki hui", "i am tired"),
        ("kamzori hai", "i have weakness"),
        ("kamzori", "weakness"),
        ("bukhaar hai", "i have fever"),
        ("bukhar hai", "i have fever"),
        ("bukhar", "fever"),
        ("temperature hai", "i have fever"),
        ("khasi hai", "i have cough"),
        ("khasi", "cough"),
        ("zukam hai", "i have cold"),
        ("zukam", "cold"),
        ("nazla", "cold"),
        ("nasal", "cold"),
        ("pet mein dard", "i have stomach pain"),
        ("pet dard hai", "i have stomach pain"),
        ("pet dard", "stomach pain"),
        ("jee machlana", "nausea"),
        ("ulti aa rahi", "i have nausea"),
        ("ulti ho rahi", "i am vomiting"),
        ("neend nahi aa rahi", "i cant sleep"),
        ("neend nahi", "i cant sleep"),
        ("insomnia", "i cant sleep"),
        ("ghabrahat", "anxiety"),
        ("anxiety hai", "i have anxiety"),
        ("seene mein dard", "i have chest pain"),
        ("seena dard", "chest pain"),
        ("saans lene mein takleef", "breathing difficulty"),
        ("saans phool raha", "breathlessness"),
        ("pair mein dard", "i have leg pain"),
        ("pair dard", "leg pain"),
        ("kamar mein dard", "i have back pain"),
        ("kamar dard", "back pain"),
        ("jodo mein dard", "joint pain"),
        ("ghutne mein dard", "knee pain"),

        // Period
        ("mahwari aa gayi", "period started"),
        ("mahwari aayi", "period started"),
        ("mahwari kab aayi", "when was my last period"),
        ("mahwari kab aayegi", "when is my next period"),
        ("periods aayi", "period started"),
        ("period shuru hua", "period started"),
        ("period shuru", "period started"),
        ("period kab aaya", "when was my last period"),
        ("period kab aayega", "when is my next period"),
        ("period nahi aaya", "my period has not come"),
        ("cycle kitne din ka", "how long is my cycle"),
        ("masik dharma", "period"),
        ("mahwari", "period"),
        ("masik", "period"),
        ("agla period", "next period"),
        ("agli mahwari", "next period"),
        ("period late", "my period is late"),

        // Pregnancy
        ("garbhavati symptoms", "pregnancy symptoms"),
        ("garbhavati", "pregnant"),
        ("garbh", "pregnancy"),
        ("pregnant hoon", "i am pregnant"),
        ("baby aa raha hai", "i am expecting a baby"),
        ("baby aa rahi hai", "i am expecting a baby"),
        ("baby ne laat mari", "baby kicked"),
        ("baby hil raha hai", "baby is moving"),
        ("delivery kab hai", "when is my due date"),
        ("due date kab hai", "when is my due date"),
        ("kitne hafte", "how many weeks pregnant"),
        ("pregnancy ka weight", "pregnancy weight"),
        ("pregnancy mein dard", "pregnancy symptom pain"),
        ("ulti aa rahi pregnancy", "pregnancy nausea"),
        ("dard ho raha hai", "i have pain"),
        ("prasav", "labour"),
        ("delivery dard", "labour pain"),
        ("bachcha hil raha hai", "baby is moving"),
        ("kya khana chahiye", "what should i eat"),
        ("doctor ke liye note", "note for doctor"),
        ("delivery plan", "birth plan"),
        ("prasav yojana", "birth plan"),
        ("mood kaisa hai", "how am i feeling"),
        ("mera mood", "my mood"),

        // Navigation
        ("mujhe dikhao", "show me"),
        ("wapas jao", "go back"),
        ("band karo", "close"),
        ("shuru karo", "start"),
        ("add karo", "add"),
        ("record karo", "record"),
        ("save karo", "save"),
        ("dekhna hai", "i want to see"),
        ("check karna hai", "i want to check"),
        ("kholo", "open"),
        ("dikhao", "show"),
        ("le jao", "take me to"),
        ("kahan hai", "where is"),
        ("wapas", "go back"),
        ("naya", "new"),

        // Numbers
        ("ek sau paaintees", "135"),
        ("ek sau paitalis", "145"),
        ("ek sau pachees", "125"),
        ("ek sau pachas", "150"),
        ("ek sau chalis", "140"),
        ("ek sau saath", "170"),
        ("ek sau tees", "130"),
        ("ek sau bis", "120"),
        ("ek sau assi", "180"),
        ("ek sau", "100"),
        ("do sau", "200"),
        ("pachattar", "75"),
        ("sattar", "70"),
        ("nabbe", "90"),
        ("assi", "80"),
        ("gyarah", "11"),
        ("barah", "12"),
        ("paanch", "5"),
        ("chhe", "6"),
        ("teen", "3"),
        ("char", "4"),
        ("saat", "7"),
        ("aath", "8"),
        ("nau", "9"),
        ("das", "10"),
        ("ek", "1"),
        ("do", "2"),

        // Common expressions
        ("theek hai", "okay"),
        ("shukriya", "thank you"),
        ("accha", "okay"),
        ("batao", "tell me"),
        ("samjhao", "explain"),
        ("mujhe chahiye", "i need"),
        ("mujhe batao", "tell me"),
        ("kya hua", "what happened"),
        ("kaise hai", "how is"),
        ("kitna hai", "how much is"),
        ("kab tha", "when was"),
        ("kab hai", "when is")
    ]
}
